In [3]:
import numpy as np


In [4]:
 b = np.arange(12).reshape(3,4)
 b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
b[b>1] = 0
b

array([[0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [6]:
b[b == 0] =-1
b

array([[-1,  1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1]])

In [7]:
b == -1

array([[ True, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [26]:
b = np.arange(12).reshape(3,4)
print(b)
b[np.logical_and(b > 3,b<=9)] = 0.0
b

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  1,  2,  3],
       [ 0,  0,  0,  0],
       [ 0,  0, 10, 11]])

In [27]:
b> 4

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True]])

In [30]:
a = 35
b = 62
xmin = ymin = 0.0
xmax =ymax = 1.1
x = np.linspace(xmin,xmax,a,endpoint =True)
y = np.linspace(ymin,ymax,b,endpoint = False)
print(x.shape)
print(y.shape)
x
y
 

(35,)
(62,)


array([0.        , 0.01774194, 0.03548387, 0.05322581, 0.07096774,
       0.08870968, 0.10645161, 0.12419355, 0.14193548, 0.15967742,
       0.17741935, 0.19516129, 0.21290323, 0.23064516, 0.2483871 ,
       0.26612903, 0.28387097, 0.3016129 , 0.31935484, 0.33709677,
       0.35483871, 0.37258065, 0.39032258, 0.40806452, 0.42580645,
       0.44354839, 0.46129032, 0.47903226, 0.49677419, 0.51451613,
       0.53225806, 0.55      , 0.56774194, 0.58548387, 0.60322581,
       0.62096774, 0.63870968, 0.65645161, 0.67419355, 0.69193548,
       0.70967742, 0.72741935, 0.74516129, 0.76290323, 0.78064516,
       0.7983871 , 0.81612903, 0.83387097, 0.8516129 , 0.86935484,
       0.88709677, 0.90483871, 0.92258065, 0.94032258, 0.95806452,
       0.97580645, 0.99354839, 1.01129032, 1.02903226, 1.04677419,
       1.06451613, 1.08225806])

In [32]:
import time
import numpy as np
a =34
b =56
x = np.linspace(0.0,1.1,a,endpoint =True)
y = np.linspace(0.0,1.1,b,endpoint = False)

In [34]:
t0 = time.time()
g = np.zeros((a,b))
for i in range (a):
  for j in range(b):
    g[i,j] = np.sin(2.0*np.pi*x[i]*y[j])

t1 = time.time()
print("time elapsed:{}s".format(t1-t0))

time elapsed:0.009803533554077148s


In [35]:
x2d,y2d = np.meshgrid(x,y,indexing ="ij")
print(x2d[:,0])
print (x2d[0,:])
print(y2d[0,:])
print(y2d[:,0])

[0.         0.03333333 0.06666667 0.1        0.13333333 0.16666667
 0.2        0.23333333 0.26666667 0.3        0.33333333 0.36666667
 0.4        0.43333333 0.46666667 0.5        0.53333333 0.56666667
 0.6        0.63333333 0.66666667 0.7        0.73333333 0.76666667
 0.8        0.83333333 0.86666667 0.9        0.93333333 0.96666667
 1.         1.03333333 1.06666667 1.1       ]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
[0.         0.01964286 0.03928571 0.05892857 0.07857143 0.09821429
 0.11785714 0.1375     0.15714286 0.17678571 0.19642857 0.21607143
 0.23571429 0.25535714 0.275      0.29464286 0.31428571 0.33392857
 0.35357143 0.37321429 0.39285714 0.4125     0.43214286 0.45178571
 0.47142857 0.49107143 0.51071429 0.53035714 0.55       0.56964286
 0.58928571 0.60892857 0.62857143 0.64821429 0.66785714 0.6875
 0.70714286 0.72678571 0.74642857 0.76607143 0.78

In [37]:
t0 = time.time()
g2 = np.sin(2.0*np.pi*x[i]*y[j])

t1 = time.time()
print("time elapsed:{}s".format(t1-t0))

time elapsed:0.0002224445343017578s


In [39]:
a = np.array([1,2,3,4])
b = np.array([3,43,4,4])
np.concatenate([b,a])

array([ 3, 43,  4,  4,  1,  2,  3,  4])

In [42]:
c = [9,0,8]
print(np.concatenate([a,b,c]))

[ 1  2  3  4  3 43  4  4  9  0  8]


In [43]:
grid = np.array([[1,2,3],[2,39,8]])

In [47]:
np.concatenate([grid,grid])

array([[  1,   2,   3],
       [  2, 389,   8],
       [  1,   2,   3],
       [  2, 389,   8]])

In [48]:
np.concatenate([grid,grid],axis =1)

array([[  1,   2,   3,   1,   2,   3],
       [  2, 389,   8,   2, 389,   8]])

In [51]:
y =[1,2,3,4,5,6,7,3,9]
x = np.split(y,[3,5,8])
print(x)

[array([1, 2, 3]), array([4, 5]), array([6, 7, 3]), array([9])]


In [52]:
grid = np.arange(25).reshape(5,5)
grid

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
left,right = np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]
 [20 21]]
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]]


In [55]:
x = np.arange(1,20)
print(x)
np.add.reduce(x)



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


190

In [56]:
np.multiply.reduce(x)

121645100408832000

In [57]:
np.add.accumulate(x)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190])

In [58]:
np.multiply.accumulate(x)

array([                 1,                  2,                  6,
                       24,                120,                720,
                     5040,              40320,             362880,
                  3628800,           39916800,          479001600,
               6227020800,        87178291200,      1307674368000,
           20922789888000,    355687428096000,   6402373705728000,
       121645100408832000])